import type { KeyMap } from "../types";

export const keymap: KeyMap = {
  UP: "KEYCODE_DPAD_UP",
  DOWN: "KEYCODE_DPAD_DOWN",
  LEFT: "KEYCODE_DPAD_LEFT",
  RIGHT: "KEYCODE_DPAD_RIGHT",
  OK: "KEYCODE_DPAD_CENTER",
  BACK: "KEYCODE_BACK",
  HOME: "KEYCODE_HOME",
  MENU: "KEYCODE_MENU",
  POWER: "KEYCODE_POWER",
  VOLUME_UP: "KEYCODE_VOLUME_UP",
  VOLUME_DOWN: "KEYCODE_VOLUME_DOWN",
  MUTE: "KEYCODE_VOLUME_MUTE",
  CHANNEL_UP: "KEYCODE_CHANNEL_UP",
  CHANNEL_DOWN: "KEYCODE_CHANNEL_DOWN",
  INPUT: "KEYCODE_TV_INPUT",
  PLAY: "KEYCODE_MEDIA_PLAY",
  PAUSE: "KEYCODE_MEDIA_PAUSE",
  STOP: "KEYCODE_MEDIA_STOP",
  REWIND: "KEYCODE_MEDIA_REWIND",
  FAST_FORWARD: "KEYCODE_MEDIA_FAST_FORWARD",
};
